### ISSUE TITLE
Improve sidebar colours for increased readability

### ISSUE THREAD

**Issue by jnnkky** [peerigon/mattermost-theme#2]
In my opinion the bright color of the sidebar makes it to hard to read the sidebar text and the low contrast is not good for the eyes.

I'm not sure which colours can be used but simply inverting the sidebar header and sidebar colours helps. Note that I also changed the online and away indicator color to white.

The brighter color for the sidebar header also improves the visual hierarchy of the sidebar elements and looks more natural.

**Comment by sbat** [comment]
@jannikkeye looks better. Please make a pull request.
